# Generated by Django 5.1.2 on 2025-12-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_message_date_message_hiring_status_message_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='client_approved',
            field=models.BooleanField(default=False, help_text='Set by admin. Only approved clients may send hire requests.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='client_blacklisted',
            field=models.BooleanField(default=False, help_text='If true, this user cannot hire performers.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_performer',
            field=models.BooleanField(default=False, help_text='Tick if you are available to be hired as a performer.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_potential_client',
            field=models.BooleanField(default=False, help_text='Tick if you want to hire performers.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='performer_blacklisted',
            field=models.BooleanField(default=False, help_text='If true, this user cannot be hired as a performer.'),
        ),
    ]
