# Generated by Django 5.1.2 on 2026-07-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_upload_users_uploa_profile_6a9f40_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='razorpayx_contact_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='profile',
            name='razorpayx_fund_account_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
