# Generated by Django 4.2.7 on 2026-09-01 08:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_add_feed_search_trgm"),
        ("users", "0016_client_performer"),
    ]

    operations = []
