apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
  namespace: artkhoj
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: migrate
          image: ghcr.io/datatwine/createscale:latest
          command: ["python", "manage.py", "migrate", "--noinput"]
          envFrom:
            - secretRef:
                name: artkhoj-env
