apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-discovery
  namespace: artkhoj
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-discovery
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods", "endpoints", "services"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-discovery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-discovery
subjects:
  - kind: ServiceAccount
    name: prometheus-discovery
    namespace: artkhoj
---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-discovery-token
  namespace: artkhoj
  annotations:
    kubernetes.io/service-account.name: prometheus-discovery
type: kubernetes.io/service-account-token
