{
 "title": "prometheus_1.0",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Failure by specific View (rough)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(10,\r\n  sum by (status, request)(\r\n    rate(nginx_http_requests_total{status=~\"5..\"}[5m])\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failures/sec (Nginx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (status)(\r\n  rate(nginx_http_requests_total{status=~\"5..\"}[$__rate_interval])\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Django Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (view, method, status)(\r\n  rate(django_http_responses_total_by_status_view_method_total{status=~\"4..|5..\"}[$__rate_interval])\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (view, method) (\r\n  rate(django_http_requests_total_by_view_transport_method_total[5m])\r\n)\r\n\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by (view, method) (\r\n  increase(django_http_requests_total_by_view_transport_method_total[5m])\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "(\r\n  sum by (view, method) (rate(django_http_requests_latency_seconds_by_view_method_sum[5m]))\r\n/\r\n  sum by (view, method) (rate(django_http_requests_latency_seconds_by_view_method_count[5m]))\r\n) * 1000\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p95 latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, view, method) (\r\n    rate(django_http_requests_latency_seconds_by_view_method_bucket[5m])\r\n  )\r\n) * 1000\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}