apiVersion: 1
datasources:
  - name: Prometheus
    uid: prometheus        # <— fixed UID so the dashboard JSON can refer to it
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
