# Generated by Django 5.1.2 on 2026-02-23 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='engagement',
            index=models.Index(fields=['client', 'status', 'date'], name='bookings_en_client__030a57_idx'),
        ),
        migrations.AddIndex(
            model_name='engagement',
            index=models.Index(fields=['performer', 'status', 'date'], name='bookings_en_perform_36d4f9_idx'),
        ),
        migrations.AddIndex(
            model_name='engagement',
            index=models.Index(fields=['status', 'date', 'time'], name='bookings_en_status_c14721_idx'),
        ),
    ]
