# Generated by Django 5.1.2 on 2026-05-27 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_engagement_bookings_en_client__030a57_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('performer', 'Performer')], max_length=16),
        ),
        migrations.AddField(
            model_name='engagement',
            name='dispute_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='dispute_resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='disputed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='fee',
            field=models.PositiveIntegerField(blank=True, help_text='Locked-in fee in rupees, snapshot from performer profile at hire time.', null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid (in escrow)'), ('released', 'Released to performer'), ('refunded', 'Refunded to client')], db_index=True, default='unpaid', max_length=16),
        ),
        migrations.AddField(
            model_name='engagement',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='Total in rupees')),
                ('platform_fee', models.PositiveIntegerField(default=0)),
                ('performer_share', models.PositiveIntegerField(default=0)),
                ('razorpay_order_id', models.CharField(max_length=64, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('razorpay_transfer_id', models.CharField(blank=True, max_length=64)),
                ('razorpay_refund_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('created', 'Order created'), ('captured', 'Payment captured (in escrow)'), ('released', 'Transferred to performer'), ('refunded', 'Refunded to client'), ('failed', 'Failed')], db_index=True, default='created', max_length=16)),
                ('raw_webhook_log', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.engagement')),
            ],
            options={
                'indexes': [models.Index(fields=['engagement', 'status'], name='bookings_pa_engagem_c5e6a7_idx')],
            },
        ),
    ]
