# Generated by Django 5.1.2 on 2026-08-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0005_engagement_payout_initiated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="engagement",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Unpaid"),
                    ("paid", "Paid (secured)"),
                    ("payout_processing", "Payout processing"),
                    ("payout_failed", "Payout failed — needs attention"),
                    ("released", "Released to performer"),
                    ("refund_pending", "Refund pending"),
                    ("refunded", "Refunded to client"),
                ],
                db_index=True,
                default="unpaid",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Order created"),
                    ("captured", "Payment captured"),
                    ("payout_processing", "Payout processing"),
                    ("payout_failed", "Payout failed"),
                    ("payout_reversed", "Payout reversed after settlement"),
                    ("released", "Released to performer"),
                    ("refund_pending", "Refund pending"),
                    ("refunded", "Refunded to client"),
                    ("refund_failed", "Refund failed"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="created",
                max_length=20,
            ),
        ),
    ]
