# Generated by Django 5.1.2 on 2026-08-14 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_engagement_payment_status_alter_payment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('client_to_performer', 'Client reviewed performer'), ('performer_to_client', 'Performer reviewed client')], max_length=20)),
                ('rating', models.PositiveSmallIntegerField(help_text='Score out of 10 (0–10).')),
                ('comment', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookings.engagement')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['subject', '-created_at'], name='bookings_re_subject_4c5e85_idx')],
                'constraints': [models.UniqueConstraint(fields=('engagement', 'author'), name='one_review_per_author_per_engagement')],
            },
        ),
    ]
